ALTER TABLE exercises ADD COLUMN equipment TEXT NOT NULL DEFAULT '';
ALTER TABLE exercises ADD COLUMN difficulty TEXT NOT NULL DEFAULT 'beginner';
ALTER TABLE exercises ADD COLUMN instructions TEXT NOT NULL DEFAULT '';
ALTER TABLE exercises ADD COLUMN tips TEXT NOT NULL DEFAULT '';
